apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: k8s-seueur-image-watcher
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
