# This rule is not used by the project k8s-seueur-image-watcher itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to vrtn14.vrtn14.sr resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-seueur-image-watcher
    app.kubernetes.io/managed-by: kustomize
  name: seueurimagewatcher-viewer-role
rules:
- apiGroups:
  - vrtn14.vrtn14.sr
  resources:
  - seueurimagewatchers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vrtn14.vrtn14.sr
  resources:
  - seueurimagewatchers/status
  verbs:
  - get
