//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeueurImageWatcher) DeepCopyInto(out *SeueurImageWatcher) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeueurImageWatcher.
func (in *SeueurImageWatcher) DeepCopy() *SeueurImageWatcher {
	if in == nil {
		return nil
	}
	out := new(SeueurImageWatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SeueurImageWatcher) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeueurImageWatcherList) DeepCopyInto(out *SeueurImageWatcherList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SeueurImageWatcher, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeueurImageWatcherList.
func (in *SeueurImageWatcherList) DeepCopy() *SeueurImageWatcherList {
	if in == nil {
		return nil
	}
	out := new(SeueurImageWatcherList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SeueurImageWatcherList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeueurImageWatcherSpec) DeepCopyInto(out *SeueurImageWatcherSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeueurImageWatcherSpec.
func (in *SeueurImageWatcherSpec) DeepCopy() *SeueurImageWatcherSpec {
	if in == nil {
		return nil
	}
	out := new(SeueurImageWatcherSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeueurImageWatcherStatus) DeepCopyInto(out *SeueurImageWatcherStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeueurImageWatcherStatus.
func (in *SeueurImageWatcherStatus) DeepCopy() *SeueurImageWatcherStatus {
	if in == nil {
		return nil
	}
	out := new(SeueurImageWatcherStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeueurWebhookConfig) DeepCopyInto(out *SeueurWebhookConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeueurWebhookConfig.
func (in *SeueurWebhookConfig) DeepCopy() *SeueurWebhookConfig {
	if in == nil {
		return nil
	}
	out := new(SeueurWebhookConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SeueurWebhookConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeueurWebhookConfigList) DeepCopyInto(out *SeueurWebhookConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SeueurWebhookConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeueurWebhookConfigList.
func (in *SeueurWebhookConfigList) DeepCopy() *SeueurWebhookConfigList {
	if in == nil {
		return nil
	}
	out := new(SeueurWebhookConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SeueurWebhookConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeueurWebhookConfigSpec) DeepCopyInto(out *SeueurWebhookConfigSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeueurWebhookConfigSpec.
func (in *SeueurWebhookConfigSpec) DeepCopy() *SeueurWebhookConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SeueurWebhookConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeueurWebhookConfigStatus) DeepCopyInto(out *SeueurWebhookConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeueurWebhookConfigStatus.
func (in *SeueurWebhookConfigStatus) DeepCopy() *SeueurWebhookConfigStatus {
	if in == nil {
		return nil
	}
	out := new(SeueurWebhookConfigStatus)
	in.DeepCopyInto(out)
	return out
}
